#!/bin/bash

# Auth System Quick Reference
# Use this to quickly understand the authentication system

echo "=== FOREX TRADING APP - AUTHENTICATION SYSTEM ==="
echo ""
echo "📋 QUICK REFERENCE"
echo ""
echo "1. BACKEND FILES"
echo "   ├─ src/services/auth.js       - Core auth logic"
echo "   ├─ src/routes/auth.js         - API endpoints"
echo "   ├─ src/middleware/auth.js     - Token verification"
echo "   ├─ src/utils/logger.js        - Logging system"
echo "   └─ logs/                      - Log files (generated)"
echo ""
echo "2. FRONTEND FILES"
echo "   ├─ src/services/auth.ts       - API client"
echo "   ├─ src/context/AuthContext.tsx - State management"
echo "   └─ src/screens/Auth/           - Auth UI screens"
echo ""
echo "3. API ENDPOINTS"
echo "   POST   /auth/register         - Create new account"
echo "   POST   /auth/login            - Login user"
echo "   POST   /auth/trial/start      - Activate trial"
echo "   GET    /auth/me               - Get current user"
echo "   POST   /auth/password/change  - Change password"
echo ""
echo "4. PASSWORD REQUIREMENTS"
echo "   ✓ Minimum 8 characters"
echo "   ✓ At least 1 UPPERCASE letter"
echo "   ✓ At least 1 lowercase letter"
echo "   ✓ At least 1 number (0-9)"
echo ""
echo "5. USER FLOW"
echo "   Register → Trial Activation → Login → Main App"
echo ""
echo "6. FRONTEND USAGE"
echo "   import { useAuth } from 'src/context/AuthContext'"
echo "   const { login, register, user, isLoading } = useAuth()"
echo ""
echo "7. LOG FILES"
echo "   Location: backend/logs/"
echo "   ├─ app.log       - General logs"
echo "   └─ error.log     - Errors & warnings"
echo ""
echo "8. CONFIGURATION"
echo "   Backend: backend/src/config.js"
echo "   Frontend: src/config/app.ts"
echo ""
echo "9. DOCUMENTATION"
echo "   Read: AUTHENTICATION.md (detailed guide)"
echo ""
echo "10. TESTING"
echo "    curl -X POST http://localhost:4000/auth/login \\"
echo "      -H 'Content-Type: application/json' \\"
echo "      -d '{\"email\": \"user@example.com\", \"password\": \"Password123\"}'"
echo ""
echo "11. DEBUG TIPS"
echo "    - Check backend/logs/ for operation logs"
echo "    - Enable DEBUG in logger for detailed output"
echo "    - Test endpoints with Postman"
echo "    - Use React DevTools to inspect auth state"
echo ""
echo "12. SECURITY CHECKLIST"
echo "    ✓ Passwords hashed with bcryptjs"
echo "    ✓ JWT tokens verified on protected routes"
echo "    ✓ Trial status checked on every request"
echo "    ✓ Input validation on all endpoints"
echo "    ✓ Passwords never returned in responses"
echo ""
echo "=== QUICK START ==="
echo ""
echo "To test the system:"
echo ""
echo "1. Start backend:  cd backend && npm run dev"
echo "2. Start frontend: npm start"
echo "3. Register user in app or use curl"
echo "4. Check logs:     tail -f backend/logs/app.log"
echo ""
echo "=== COMMON ERRORS ==="
echo ""
echo "Error: 'Invalid email or password'"
echo "  → Check email and password are correct"
echo "  → Verify user exists in database"
echo ""
echo "Error: 'Free trial must be activated'"
echo "  → Run auth/trial/start endpoint after registration"
echo ""
echo "Error: 'Password must contain...'"
echo "  → Password missing: uppercase, lowercase, or number"
echo "  → Password too short (minimum 8 characters)"
echo ""
echo "Error: 'Missing authentication token'"
echo "  → Request needs Authorization header with Bearer token"
echo ""
echo "=== NEXT STEPS ==="
echo ""
echo "1. Read AUTHENTICATION.md for complete documentation"
echo "2. Review src/screens/Auth/AuthScreenExample.tsx"
echo "3. Integrate useAuth hook in your screens"
echo "4. Test all flows with real device/emulator"
echo ""
