import { CurrencyPair, Trade } from '../types/market';
import { AIRecommendation } from '../types/ai';
import type { MarketAlert } from '../types/alerts';

export const mockCurrencyPairs: CurrencyPair[] = [
  {
    id: '1',
    symbol: 'EUR/USD',
    base: 'EUR',
    quote: 'USD',
    price: 1.08542,
    change: 0.00123,
    changePercent: 0.11,
    high24h: 1.08650,
    low24h: 1.08420,
    volume24h: 1250000000,
  },
  {
    id: '2',
    symbol: 'GBP/USD',
    base: 'GBP',
    quote: 'USD',
    price: 1.26458,
    change: -0.00234,
    changePercent: -0.18,
    high24h: 1.26700,
    low24h: 1.26300,
    volume24h: 850000000,
  },
  {
    id: '3',
    symbol: 'USD/JPY',
    base: 'USD',
    quote: 'JPY',
    price: 149.856,
    change: 0.234,
    changePercent: 0.16,
    high24h: 150.100,
    low24h: 149.500,
    volume24h: 950000000,
  },
  {
    id: '4',
    symbol: 'USD/CHF',
    base: 'USD',
    quote: 'CHF',
    price: 0.87542,
    change: -0.00056,
    changePercent: -0.06,
    high24h: 0.87600,
    low24h: 0.87450,
    volume24h: 450000000,
  },
  {
    id: '5',
    symbol: 'AUD/USD',
    base: 'AUD',
    quote: 'USD',
    price: 0.65234,
    change: 0.00112,
    changePercent: 0.17,
    high24h: 0.65300,
    low24h: 0.65100,
    volume24h: 650000000,
  },
  {
    id: '6',
    symbol: 'USD/CAD',
    base: 'USD',
    quote: 'CAD',
    price: 1.34567,
    change: -0.00089,
    changePercent: -0.07,
    high24h: 1.34700,
    low24h: 1.34400,
    volume24h: 550000000,
  },
  {
    id: '7',
    symbol: 'NZD/USD',
    base: 'NZD',
    quote: 'USD',
    price: 0.59876,
    change: 0.00045,
    changePercent: 0.08,
    high24h: 0.59950,
    low24h: 0.59800,
    volume24h: 350000000,
  },
  {
    id: '8',
    symbol: 'EUR/GBP',
    base: 'EUR',
    quote: 'GBP',
    price: 0.85842,
    change: 0.00123,
    changePercent: 0.14,
    high24h: 0.85900,
    low24h: 0.85700,
    volume24h: 450000000,
  },
];

export const mockMarketAlerts: MarketAlert[] = [
  {
    id: 'a1',
    pair: 'EUR/USD',
    type: 'PRICE_ALERT',
    title: 'Price alert triggered near key level',
    message: 'Breakout above 1.0840 with rising volume. Institutional accumulation detected.',
    timeframe: '15m',
    changePercent: 0.21,
    minutesAgo: 2,
  },
  {
    id: 'a2',
    pair: 'GBP/JPY',
    type: 'VOLATILITY',
    title: 'Volatility spike detected',
    message: 'Spread widening + fast momentum. Consider reduced size and wider stop placement.',
    timeframe: '5m',
    changePercent: -0.44,
    minutesAgo: 5,
  },
  {
    id: 'a3',
    pair: 'USD/JPY',
    type: 'MARKET_NEWS',
    title: 'Macro headline risk elevated',
    message: 'Policy uncertainty increasing intraday whipsaw. Wait for confirmation after the next candle close.',
    timeframe: '1h',
    minutesAgo: 12,
  },
  {
    id: 'a4',
    pair: 'XAU/USD',
    type: 'VOLATILITY',
    title: 'Large impulse candle',
    message: 'Momentum shift detected. Watch retest for higher-probability entry.',
    timeframe: '15m',
    changePercent: 0.83,
    minutesAgo: 18,
  },
  {
    id: 'a5',
    pair: 'AUD/USD',
    type: 'PRICE_ALERT',
    title: 'Support test in progress',
    message: 'Repeated tests of support with weakening bids. Breakdown risk rising.',
    timeframe: '1h',
    changePercent: -0.17,
    minutesAgo: 26,
  },
];

export const mockTrades: Trade[] = [
  {
    id: '1',
    pair: 'EUR/USD',
    type: 'buy',
    amount: 0.1,
    price: 1.08420,
    timestamp: new Date(Date.now() - 3600000),
  },
  {
    id: '2',
    pair: 'GBP/USD',
    type: 'sell',
    amount: 0.05,
    price: 1.26600,
    timestamp: new Date(Date.now() - 7200000),
  },
  {
    id: '3',
    pair: 'USD/JPY',
    type: 'buy',
    amount: 0.2,
    price: 149.500,
    timestamp: new Date(Date.now() - 10800000),
  },
  {
    id: '4',
    pair: 'AUD/USD',
    type: 'buy',
    amount: 0.15,
    price: 0.65100,
    timestamp: new Date(Date.now() - 14400000),
  },
  {
    id: '5',
    pair: 'EUR/GBP',
    type: 'sell',
    amount: 0.08,
    price: 0.85700,
    timestamp: new Date(Date.now() - 18000000),
  },
  {
    id: '6',
    pair: 'EUR/USD',
    type: 'buy',
    amount: 0.1,
    price: 1.08200,
    timestamp: new Date(Date.now() - 86400000),
    profit: 24.20,
  },
  {
    id: '7',
    pair: 'GBP/USD',
    type: 'sell',
    amount: 0.05,
    price: 1.26800,
    timestamp: new Date(Date.now() - 172800000),
    profit: -7.10,
  },
];

export const mockAIRecommendations: AIRecommendation[] = [
  {
    id: '1',
    pair: 'EUR/USD',
    recommendation: 'BUY',
    confidence: 78,
    insight: 'Strong bullish momentum with RSI breaking above 60. ECB rate decision expected to be dovish, supporting EUR strength. Technical analysis shows clear uptrend with support at 1.0820.',
    entryPrice: 1.08542,
    targetPrice: 1.0920,
    stopLoss: 1.0820,
    timeframe: '4H',
  },
  {
    id: '2',
    pair: 'GBP/USD',
    recommendation: 'SELL',
    confidence: 82,
    insight: 'Cable showing weakness against USD backdrop. Bank of England minutes suggest potential rate cuts. Bearish engulfing pattern formed at resistance level 1.2680.',
    entryPrice: 1.26458,
    targetPrice: 1.2580,
    stopLoss: 1.2680,
    timeframe: '1H',
  },
  {
    id: '3',
    pair: 'USD/JPY',
    recommendation: 'WAIT',
    confidence: 65,
    insight: 'Mixed signals in USD/JPY. BoJ policy uncertainty creating volatility. Wait for clearer direction before entering. Current range: 149.50 - 150.10.',
    timeframe: '2H',
  },
  {
    id: '4',
    pair: 'USD/CHF',
    recommendation: 'BUY',
    confidence: 71,
    insight: 'USD/CHF testing key support level. SNB maintaining cautious stance while Fed signals potential pause. Bullish divergence on MACD suggests potential reversal.',
    entryPrice: 0.87542,
    targetPrice: 0.8820,
    stopLoss: 0.8720,
    timeframe: '1H',
  },
  {
    id: '5',
    pair: 'AUD/USD',
    recommendation: 'SELL',
    confidence: 75,
    insight: 'Australian dollar under pressure from RBA rate cut expectations. Commodity prices weakening, particularly iron ore. Bearish head and shoulders pattern forming.',
    entryPrice: 0.6542,
    targetPrice: 0.6480,
    stopLoss: 0.6580,
    timeframe: '4H',
  },
];

